#!/bin/bash

osmconvert="osmconvert"
osmfilter="osmfilter"

echo ------------------
start=`date +%H:%M:%S`
echo `date +%H:%M:%S` creating $1.hnr.osm
echo ------------------

$osmconvert $1 --all-to-nodes --out-o5m > $1.o5m
$osmfilter $1.o5m --keep-nodes="addr:*=" --keep-tags="all addr:*= shop= amenity= tourism= name= operator= power=substation street_lamp" -o=$1.hnr.osm
rm $1.o5m

echo ------------------
echo  $start-`date +%H:%M:%S` filter finished
echo ------------------
exit 0
