######################################################################
# Automatically generated by qmake (2.01a) So. Jun 19 12:03:49 2011
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += HouseNumberTest.cpp HouseNumber.cpp
HEADERS += HouseNumber.h
