######################################################################
# Automatically generated by qmake (2.01a) So. Jun 19 12:03:49 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += xml

# Input
SOURCES += housenumbervalidator.cpp
SOURCES += HouseNumber.cpp
HEADERS += HouseNumber.h
