#!/bin/bash

function run {
	echo ------------------
	echo run for austria
	echo ------------------
	
	mkdir austria
	cd austria
	
	mv index.html index.html~
	
	wget http://download.geofabrik.de/osm/europe/ -O index.html
	d=`cat index.html | grep austria.osm.pbf | sed -e "s/\`date +%Y\`.*//g" | sed -e "s/.*>//g" | grep -v \`date +%d\` | wc -l`
	cdate=`stat -c %y dupes.txt | awk '{ printf austria "\n"}'`
	
	if [ $cdate == `date +%Y-%m-%d` ]; then
		echo \!\!\!\!\!\!\!\!\!\!\!\!\!\!\!\!\!\!
		echo Already run? Aborting austria...
		echo \!\!\!\!\!\!\!\!\!\!\!\!\!\!\!\!\!\!
	elif [ ! $d  == 0 ]; then
		echo \!\!\!\!\!\!\!\!\!\!\!\!\!\!\!\---
		echo austria.osm.pbf seems to be too old. Aborting austria...
		echo \!\!\!\!\!\!\!\!\!\!\!\!\!\!\!\---
	else
		rm austria.*
		cp ../filter .
		cp ../housenumbervalidator .
		wget http://download.geofabrik.de/osm/europe/austria.osm.pbf
		if [ ! $? -eq 0 ]; then
			echo download problem
			exit 1;
		fi
		nice -n 19 ./filter austria.osm.pbf
		if [ ! $? -eq 0 ]; then
			echo filter problem
			exit 3;
		fi
		nice -n 19 ./housenumbervalidator austria.osm.pbf.hnr.osm -l -l=`wc -l austria.osm.pbf.hnr.osm | awk '{ printf $1 "\n"}'` -ac=AT -cpn -css -iih -cpc=4
		if [ ! $? -eq 0 ]; then
			echo housenumbervalidator problem austria
			exit 4;
		fi
		
		grep -v -P "\tNL\t|\tBE\t|\tDK\t|\tFR\t|\tLU\t|\tNL\t|\tCH\t|\tAT\t|\tPL\t|\tCZ\t" broken.txt | grep -v --file=../html/reports.txt > brok
		echo $((`cat broken.txt | wc -l`-`cat brok | wc -l`)) foreign lines removed
		mv brok broken.txt
		
		grep dupes.txt -v --file=../html/reports.txt > dupes
		mv dupes dupes.txt
		
		echo Dupes:
		wc -l dupes.txt
		echo Broken:
		wc -l broken.txt
		
		echo ------------------
		echo Finished austria!
		echo ------------------
	fi
	
	cd ..
}

run
