#!/bin/bash

function run {
	echo ------------------
	echo run for austria
	echo ------------------
	
	mkdir austria
	cd austria
	
	mv index.html index.html~
	
	wget http://download.geofabrik.de/openstreetmap/europe/ -O index.html
	d=`cat index.html | grep austria.osm.pbf | sed -e "s/\`date +%Y\`.*//g" | sed -e "s/.*>//g" | grep -v \`date +%d\` | wc -l`
	cdate=`stat -c %y dupes.txt | awk '{ printf $1 "\n"}'`
	
	if [ $cdate == `date +%Y-%m-%d` ]; then
		echo $(tput setaf 3)\!\!\!\!\!\!\!\!\!\!\!\!\!\!\!\!\!\!
		echo Already run? Aborting austria...
		echo \!\!\!\!\!\!\!\!\!\!\!\!\!\!\!\!\!\!$(tput sgr0)
	elif [ ! $d  == 0 ]; then
		echo $(tput setaf 1)\!\!\!\!\!\!\!\!\!\!\!\!\!\!\!\!\!\!
		echo austria.osm.pbf seems to be too old. Aborting austria...
		echo \!\!\!\!\!\!\!\!\!\!\!\!\!\!\!\!\!\!$(tput sgr0)
	else
		rm austria.*
		cp ../filter .
		cp ../housenumbervalidator .
		wget http://download.geofabrik.de/osm/europe/austria.osm.pbf
		if [ ! $? -eq 0 ]; then
			echo $(tput bold)$(tput setaf 1)download problem$(tput sgr0)
			exit 1;
		fi
		nice -n 19 ./filter austria.osm.pbf
		if [ ! $? -eq 0 ]; then
			echo $(tput bold)$(tput setaf 1)filter problem$(tput sgr0)
			exit 3;
		fi
		nice -n 19 ./housenumbervalidator austria.osm.pbf.hnr.osm -l -l=`wc -l austria.osm.pbf.hnr.osm | awk '{ printf $1 "\n"}'` -ac=AT -cpn -css -cpc=4
		if [ ! $? -eq 0 ]; then
			echo $(tput bold)$(tput setaf 1)housenumbervalidator problem austria$(tput sgr0)
			exit 4;
		fi
		
		grep -v -P "\tDE\t|\tIT\t|\tLI\t|\tSK\t|\tCH\t|\tSI\t|\tCZ\t|\tHU\t" broken.txt | grep -v --file=../html/reports.txt > brok
		echo $((`cat broken.txt | wc -l`-`cat brok | wc -l`)) foreign lines removed
		mv brok broken.txt
		
		grep dupes.txt -v --file=../html/reports.txt > dupes
		mv dupes dupes.txt
		
		echo Dupes:
		wc -l dupes.txt
		echo Broken:
		wc -l broken.txt
		
		echo $(tput setaf 2)------------------
		echo Finished austria!
		echo ------------------$(tput sgr0)
	fi
	
	cd ..
}

run
